# Build and deploy Python project to Azure Linux Web App
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Free Trial(30480133-5647-4971-ae95-37070ce1148c)'
    appType: 'webAppLinux'
    WebAppName: 'redhatmoon'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    RuntimeStack: 'PYTHON|3.10'

trigger:
  - master

variables:
  # Azure service connection for deployment
  azureServiceConnectionId: 'd70fdf7f-2c6e-456b-aca9-b188b0280394'

  # Web app name
  webAppName: 'linux-web-jahapp'

  # Linux agent image for build job
  linuxAgentImage: 'ubuntu-latest'

  # Environment name
  environmentName: 'linux-web-jahapp'

  # Project root folder (containing manage.py)
  projectRoot: $(System.DefaultWorkingDirectory)

  # Python version
  pythonVersion: '3.7'

stages:
  - stage: Build
    displayName: Build Stage
    jobs:
      - job: BuildJob
        pool:
          vmImage: $(linuxAgentImage)
        steps:
          - task: UsePythonVersion@0
            displayName: Use Python $(pythonVersion)
            inputs:
              versionSpec: $(pythonVersion)

          - script: |
              python -m venv antenv
              source antenv/bin/activate
              python -m pip install --upgrade pip
              pip install setup.py
              pip install -r requirements.txt
            workingDirectory: $(projectRoot)
            displayName: Install requirements

          - task: ArchiveFiles@2
            displayName: Archive files
            inputs:
              rootFolderOrFile: $(projectRoot)
              includeRootFolder: false
              archiveType: zip
              archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
              replaceExistingArchive: true

          - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
            displayName: Upload package
            artifact: drop

  - stage: Deploy
    displayName: Deploy Web App
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: DeploymentJob
        pool:
          vmImage: $(linuxAgentImage)
        environment: $(environmentName)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: UsePythonVersion@0
                  displayName: Use Python version
                  inputs:
                    versionSpec: $(pythonVersion)

                - task: AzureWebApp@1
                  displayName: Deploy Azure Web App
                  inputs:
                    azureSubscription: '30480133-5647-4971-ae95-37070ce1148c'
                    appName: $(webAppName)
                    package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
