trigger:  
- master # Or the branch of your choice

pool:
  vmImage: 'ubuntu-latest' 

variables:
  imageName: 'shivamspace/$(Build.Repository.Name):$(Build.BuildId)' # For Docker Hub
  dockerHubUsername: 'shivamspace'
  dockerHubPassword: 'Redhat@3439' 

stages:
- stage: Build
  displayName: Build and Push Image
  jobs:
  - job: 
    displayName: Build Docker Image
    steps:
    - task: Docker@2
      displayName: 'Login to Docker Hub'
      inputs:
        command: login
        containerRegistry: docker.io 
        repository: '' # No repository needed for login
        username: $(dockerHubUsername)
        password: $(dockerHubPassword)

    - task: Docker@2
      displayName: Build image
      inputs:
        repository: $(imageName) 
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile' 
        tags: latest

    - task: Docker@2
      displayName: Push image
      inputs:
        repository: $(imageName)
        command: push
        tags: latest

# ... (Previous stages remain the same)

- stage: Deploy
  displayName: Deploy to ACA
  jobs:
  - job: 
    displayName: Deploy to Container App
    steps:
    - task: AzureCLI@2
      displayName: 'Deploy to Azure Container App (with port)'
      inputs:
        azureSubscription: 'my-service-connection' 
        scriptType: bash 
        scriptLocation: inlineScript  
        inlineScript: |
          az containerapp update \
            --name my-container-app \  
            --resource-group DefaultResourceGroup-EUS \ 
            --image $(imageName):latest \
            --target-port 5000  # Specify port for ACA

